In [1]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 14.6 ms, sys: 11.1 ms, total: 25.7 ms
Wall time: 31.3 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 618 ms, sys: 188 ms, total: 805 ms
Wall time: 842 ms


## 4.1 The NumPy ndarray: A Multidimensional Array Object

In [4]:
data = np.random.randn(2, 3)
data

array([[-0.15440962,  1.21429473,  1.05906202],
       [-0.46844722,  1.40770531, -1.19218852]])

In [5]:
data * 10

array([[ -1.54409625,  12.14294725,  10.59062021],
       [ -4.68447218,  14.07705306, -11.92188519]])

In [6]:
data + data

array([[-0.30881925,  2.42858945,  2.11812404],
       [-0.93689444,  2.81541061, -2.38437704]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

### Creating ndarrays

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2, 3, 2))

array([[[-0.00000000e+000, -0.00000000e+000],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[-0.00000000e+000, -0.00000000e+000],
        [ 1.39497555e+165,  6.17863252e-042],
        [-1.49458115e-154,  8.38747931e-309]]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types and ndarrays

In [21]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

In [23]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [25]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [26]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [27]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [28]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [29]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### Arithmetic with NumPy Arrays

In [31]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [33]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [35]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [37]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [38]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [39]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr[5]

5

In [41]:
arr[5:8]

array([5, 6, 7])

In [42]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [43]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [44]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [46]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [48]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [49]:
arr2d[0][2]

3

In [51]:
arr2d[0,2]

3

In [52]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr3d[1,0]

array([7, 8, 9])

In [57]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [58]:
x[0]

array([7, 8, 9])

#### Indexing with slices

In [59]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [60]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [61]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [64]:
arr2d[1, :2]

array([4, 5])

In [65]:
arr2d[:2, 2]

array([3, 6])

In [66]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [67]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing